language: python
python: '2.7'
cache: pip
matrix:
  fast_finish: true
install:
- pip install --disable-pip-version-check --upgrade pip
- pip install -r requirements.txt
- cd ${HOME}
- wget https://github.com/cornell-brg/pydgin/archive/master.zip
- unzip master.zip
- mv pydgin-master pydgin
- cd ${HOME}
- wget https://bitbucket.org/pypy/pypy/get/default.tar.gz
- tar xf default.tar.gz --transform 's/pypy-pypy-[0-9a-f]\+/pypy/' --exclude 'pypy-pypy-*/pytest_cov.py'
- cd $TRAVIS_BUILD_DIR
- export PYTHONPATH=${PYTHONPATH}:${HOME}/pydgin/
script:
- py.test -n 4 -rxs --color=yes --cov-config .coveragerc --cov=revelation revelation/test/ scripts/test/
- cd docs
- make html
- make linkcheck
- cd ..
- PYTHONPATH=${HOME}/pydgin/:. ${HOME}/pypy/rpython/bin/rpython --no-pdb --opt=jit revelation/sim.py
- if [ "${TRAVIS_PULL_REQUEST}" == "false" ] && [ "${TRAVIS_BRANCH}" == "master" ] ;
    then PYTHONPATH=${HOME}/pydgin/:. ${HOME}/pypy/rpython/bin/rpython --no-pdb --opt=jit revelation/sim.py --debug ;
  fi
- if [ "${TRAVIS_PULL_REQUEST}" == "false" ] && [ "${TRAVIS_BRANCH}" == "master" ] ;
    then PYTHONPATH=${HOME}/pydgin/:. ${HOME}/pypy/rpython/bin/rpython --no-pdb -O2 revelation/sim.py ;
  fi
- mkdir bin
- mv pydgin-revelation-* bin/
- echo "Translated Revelation binaries:" bin/*
after_success:
- coveralls
- ./scripts/deploy.sh
