language: python

install:
    - sudo apt-get install wget
    - pip install -r requirements.txt
    - pip install coveralls
    - cd $HOME
    - wget https://github.com/cornell-brg/pydgin/archive/master.zip
    - unzip master.zip
    - mv pydgin-master pydgin
    - export PYTHONPATH=${PYTHONPATH}:${HOME}/pydgin/
    - cd $TRAVIS_BUILD_DIR

python:
    - "2.7"

script:
    - py.test -n 4 --cov-report term-missing --cov epiphany epiphany/test/

after_success: coveralls
